config/routes.rb
Rails.application.routes.draw do
  root :to => 'lessons#index'

  resources :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :name, :presence => true
  validates :content, :presence => true
  validates :number, :presence => true

  def next
    nextLessonNumber = self.number.+(1)
    Lesson.all.each do |lesson|
      if lesson.number === nextLessonNumber
        return lesson
      end
    end
    return null
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(params[:lesson])
      redirect_to lessons_path
    else
      render :edit
    end
  end

private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learnhow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="app/assets/stylesheets/bootstrap.css" media="screen" title="no title" charset="utf-8">
</head>
<body>
  <h1></h1>
  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for @lesson do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.submit "Submit", :class => "btn btn-danger" %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit lesson</h1>

<%= render 'form' %>

app/views/lessons/index.html.erb
<h1>Lessons</h1>

<p><%= link_to "Create new lesson", new_lesson_path %></p>

<ul>
  <% @lessons.each do |lesson| %>
    <li><%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>

<h4><%= @lesson.content %></h4>

<p><%= link_to "Next", lesson_path(@lesson.next) %></p>

<p><%= link_to "Edit", edit_lesson_path(@lesson) %>

<p>
  <%= link_to 'Return to lessons', lessons_path %>
</p>